export const cartData = [
    {
        imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJOyWHuKfjjud0QNsrNJ1YTjgLOwG3-MJ5DlnwEXcH-j7ZSvoFJyCLfgz5Br4H7Eqn96o&usqp=CAU",
        postedTime: "Il y a 1 heure",
        discussions: 12,
        title: "Électronique Volumineuse",
        weight: "15 kg",
        distance: "500 km",
        price: "150 €",
        description:
            "Colis volumineux contenant divers articles électroniques. Nécessite une manipulation soigneuse et un environnement à température contrôlée.",
        tags: [
            "Électronique",
            "Fragile",
            "Livraison Express",
            "Livraison Standard",
            "Colis Volumineux",
        ],
        size: ["L", "S"],
        city: "Paris",
        dateCondition: "",
        date: "15 juin",
        manutentionType: "Au pied du véhicule",
        departure: {
            city: "Paris",
            postalCode: "75000",
            country: "France",
        },
        arrival: {
            city: "Madrid",
            postalCode: "28000",
            country: "Espagne",
        },
    },
    {
        imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJOyWHuKfjjud0QNsrNJ1YTjgLOwG3-MJ5DlnwEXcH-j7ZSvoFJyCLfgz5Br4H7Eqn96o&usqp=CAU",
        postedTime: "Il y a 3 heures",
        discussions: 5,
        title: "Colis de Vêtements",
        weight: "7 kg",
        distance: "300 km",
        price: "80 €",
        description:
            "Colis contenant des vêtements divers, nécessite un emballage standard et une livraison classique.",
        tags: ["Vêtements", "Livraison Standard", "Colis Léger", "Mode"],
        size: ["L", "M"],
        city: "Marseille",
        dateCondition: "",
        date: "20 juin",
        manutentionType: "Manutention - 1 personne",
        departure: {
            city: "London",
            postalCode: "SW1A 1AA",
            country: "United Kingdom",
        },
        arrival: {
            city: "Berlin",
            postalCode: "10115",
            country: "Germany",
        },
    },
    {
        imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJOyWHuKfjjud0QNsrNJ1YTjgLOwG3-MJ5DlnwEXcH-j7ZSvoFJyCLfgz5Br4H7Eqn96o&usqp=CAU",
        postedTime: "Il y a 5 heures",
        discussions: 8,
        title: "Ensemble de Mobilier",
        weight: "50 kg",
        distance: "200 km",
        price: "300 €",
        description:
            "Un ensemble de mobilier comprenant des chaises et des tables, nécessite une manutention robuste.",
        tags: [
            "Mobilier",
            "Lourd",
            "Livraison Standard",
            "Meubles",
            "Livraison Express",
        ],
        size: ["2XL"],
        city: "Lyon",
        dateCondition: "entre",
        date: ["15 juin", "13 nov"],
        manutentionType: "Manutention - 2 personnes",
        departure: {
            city: "New York",
            postalCode: "10001",
            country: "USA",
        },
        arrival: {
            city: "Los Angeles",
            postalCode: "90001",
            country: "USA",
        },
    },
    {
        imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJOyWHuKfjjud0QNsrNJ1YTjgLOwG3-MJ5DlnwEXcH-j7ZSvoFJyCLfgz5Br4H7Eqn96o&usqp=CAU",
        postedTime: "Il y a 2 jours",
        discussions: 3,
        title: "Livraison de Matériel de Bureau",
        weight: "25 kg",
        distance: "150 km",
        price: "120 €",
        description:
            "Envoi de matériel de bureau lourd, avec des articles tels que des imprimantes et des chaises.",
        tags: ["Bureau", "Livraison Standard", "Livraison Express", "Lourd"],
        size: ["M", "L"],
        city: "Toulouse",
        dateCondition: "entre",
        date: ["15 nov", "17 nov"],
        manutentionType: "Manutention - 1 personne",
        departure: {
            city: "Tokyo",
            postalCode: "100-0001",
            country: "Japan",
        },
        arrival: {
            city: "Seoul",
            postalCode: "04524",
            country: "South Korea",
        },
    },
    {
        imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJOyWHuKfjjud0QNsrNJ1YTjgLOwG3-MJ5DlnwEXcH-j7ZSvoFJyCLfgz5Br4H7Eqn96o&usqp=CAU",
        postedTime: "Il y a 6 heures",
        discussions: 10,
        title: "Cartons de Déménagement",
        weight: "40 kg",
        distance: "400 km",
        price: "200 €",
        description:
            "Colis de cartons pour un déménagement. Les articles sont répartis dans plusieurs petits cartons.",
        tags: [
            "Déménagement",
            "Livraison Standard",
            "Cartons",
            "Colis Volumineux",
        ],
        size: ["XL", "L"],
        city: "Bordeaux",
        dateCondition: "avant",
        date: "07 dec",
        manutentionType: "Manutention - 2 personnes",
        departure: {
            city: "Sydney",
            postalCode: "2000",
            country: "Australia",
        },
        arrival: {
            city: "Melbourne",
            postalCode: "3000",
            country: "Australia",
        },
    },
    {
        imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJOyWHuKfjjud0QNsrNJ1YTjgLOwG3-MJ5DlnwEXcH-j7ZSvoFJyCLfgz5Br4H7Eqn96o&usqp=CAU",
        postedTime: "Il y a 4 heures",
        discussions: 7,
        title: "Livraison de Vélo Électrique",
        weight: "20 kg",
        distance: "100 km",
        price: "450 €",
        description:
            "Vélo électrique, besoin de manipulation soignée pour une livraison rapide.",
        tags: ["Vélo", "Transport", "Livraison Express", "Livraison Standard"],
        size: ["L", "S"],
        city: "Nice",
        dateCondition: "avant",
        date: "06 dec",
        manutentionType: "Au pied du véhicule",
        departure: {
            city: "Cape Town",
            postalCode: "8001",
            country: "South Africa",
        },
        arrival: {
            city: "Johannesburg",
            postalCode: "2001",
            country: "South Africa",
        },
    },
];
